import type Database from 'better-sqlite3';
import { ulid } from 'ulid';
import type { NotesRepository } from '../notes/repository.js';
// `ulid` is used for the note id only — audit_log.id is INTEGER
// PRIMARY KEY AUTOINCREMENT and rejects string values ("datatype mismatch").
import type { Note } from '../notes/types.js';
import { CONCIERGE_ACTOR } from './types.js';
import type { Tier0Finding, FindingSeverity } from './mo-tier0.js';
import type { MoPatrolFindingsRepository } from './mo-patrol-findings-repository.js';

/**
 * Mo Indexing Redesign — `mo:patrol-log` note infrastructure.
 *
 * One note per folder, append-only, holds Tier 0 deterministic
 * findings + (Phase 2+) Mo activity trace. Created lazily on first
 * patrol; user-readable via the regular notes UI; MCP-readable for
 * `mcp:mo` actor only (other MCP actors get the existing per-folder
 * permission gate; `mo:` source signals system-managed).
 *
 * Body format is plain markdown so user can read / search through FTS
 * just like any other note. Each patrol pass appends a date-stamped
 * section. User-edited prose outside the date sections is preserved.
 *
 * Title is derived from the first body line per the project-wide rule
 * (`deriveTitleFromBody`); we lock it as `# Mo Patrol Log` so the
 * title never drifts.
 *
 * `actor='mcp:mo'` for every write — flows into audit_log and the
 * Activity panel. Per CLAUDE.md invariant "every MCP mutation writes
 * audit history".
 */

const PATROL_LOG_SOURCE = 'mo:patrol-log' as const;
const PATROL_LOG_ACTOR = CONCIERGE_ACTOR;
const PATROL_LOG_TITLE = '# Mo Patrol Log';

const HEADER_BLOCK = `${PATROL_LOG_TITLE}

_Auto-generated by Mo. Each patrol pass appends a section below; user prose between sections is preserved._

`;

interface PatrolNoteRow {
  id: string;
  body: string;
  updated_at: number;
}

export interface AppendFindingsOptions {
  /** Override Date.now for tests. */
  now?: number;
  /** Skip sectioning if no findings — return without writing. Default true. */
  skipEmpty?: boolean;
  /** Phase 5d — when supplied, also insert each finding into the
   *  lifecycle table (`mo_patrol_findings`) so it can be acked /
   *  dismissed / snoozed via `mo_acknowledge_finding`. The returned
   *  result includes `findingIds` in the same order as `findings`. */
  findingsRepo?: MoPatrolFindingsRepository;
}

/**
 * Find or create the `mo:patrol-log` note for a folder. Idempotent —
 * subsequent calls return the existing note. The note is created with
 * a stable header block; the body is otherwise empty until findings
 * are appended.
 */
export function ensurePatrolLogNote(
  db: Database.Database,
  notes: NotesRepository,
  folderId: string,
  now: number = Date.now(),
): Note {
  const existing = findPatrolLogNote(db, folderId);
  if (existing) {
    return notes.getById(existing.id) as Note;
  }

  // Bypass NotesRepository.create's title derivation — we want exact
  // control over the body and to set source='mo:patrol-log' which is
  // not exposed in the public NoteCreateInput schema. Direct insert is
  // fine here; we still emit an audit row for parity.
  const id = ulid();
  db.prepare(
    `INSERT INTO notes
       (id, folder_id, title, body, pinned, source, created_at, updated_at,
        deleted_at, status, position)
     VALUES (?, ?, ?, ?, 0, ?, ?, ?, NULL, 'note', NULL)`,
  ).run(id, folderId, 'Mo Patrol Log', HEADER_BLOCK, PATROL_LOG_SOURCE, now, now);

  db.prepare(
    `INSERT INTO audit_log (note_id, action, actor, ts)
     VALUES (?, ?, ?, ?)`,
  ).run(id, 'create', PATROL_LOG_ACTOR, now);

  const created = notes.getById(id);
  if (!created) {
    throw new Error('failed to ensure mo:patrol-log note (post-insert getById null)');
  }
  return created;
}

/**
 * Append a section of Tier 0 findings to the patrol-log note. No-op
 * when `findings.length === 0` and `skipEmpty !== false` — patrol
 * passes that find nothing don't churn the note. Bumps `updated_at`
 * (content change), emits an `update` audit row.
 */
export function appendFindings(
  db: Database.Database,
  notes: NotesRepository,
  folderId: string,
  findings: Tier0Finding[],
  options: AppendFindingsOptions = {},
): { note: Note; appended: number; findingIds: string[] } {
  const now = options.now ?? Date.now();
  const skipEmpty = options.skipEmpty !== false;
  if (findings.length === 0 && skipEmpty) {
    const note = ensurePatrolLogNote(db, notes, folderId, now);
    return { note, appended: 0, findingIds: [] };
  }

  const note = ensurePatrolLogNote(db, notes, folderId, now);
  const section = renderFindingsSection(findings, now);
  const newBody = note.body.endsWith('\n')
    ? note.body + section
    : note.body + '\n' + section;

  db.prepare(
    `UPDATE notes SET body = ?, title = ?, updated_at = ? WHERE id = ?`,
  ).run(newBody, deriveTitle(newBody), now, note.id);

  db.prepare(
    `INSERT INTO audit_log (note_id, action, actor, ts)
     VALUES (?, ?, ?, ?)`,
  ).run(note.id, 'update', PATROL_LOG_ACTOR, now);

  // Phase 5d — write to the lifecycle table when the caller supplied
  // the repo. Back-compat: tests / callers without the repo just keep
  // the markdown-only behavior.
  const findingIds = options.findingsRepo
    ? options.findingsRepo.insertBatch(folderId, findings, now)
    : [];

  const refreshed = notes.getById(note.id);
  if (!refreshed) {
    throw new Error('mo:patrol-log note disappeared mid-append');
  }
  return { note: refreshed, appended: findings.length, findingIds };
}

/**
 * Render one patrol section: an `## YYYY-MM-DD HH:MM UTC` heading and
 * one bullet per finding. Severity-prefixed for fast eye-scanning.
 */
export function renderFindingsSection(
  findings: Tier0Finding[],
  ts: number,
): string {
  const heading = `## ${formatUtcStamp(ts)}\n\n`;
  if (findings.length === 0) {
    return heading + '_No findings — folder looks clean._\n\n';
  }
  const sorted = [...findings].sort(severityCompare);
  const lines = sorted.map((f) => {
    const sev = severityBadge(f.severity);
    const ref = `[${f.noteId}]`;
    const titleClip = f.noteTitle.length > 80
      ? f.noteTitle.slice(0, 77) + '...'
      : f.noteTitle;
    return `- ${sev} **${f.kind}** ${ref} "${titleClip}" — ${f.message}`;
  });
  return heading + lines.join('\n') + '\n\n';
}

export function findPatrolLogNote(
  db: Database.Database,
  folderId: string,
): PatrolNoteRow | null {
  const row = db
    .prepare<[string, string], PatrolNoteRow>(
      `SELECT id, body, updated_at FROM notes
        WHERE folder_id = ? AND source = ? AND deleted_at IS NULL
        ORDER BY created_at ASC
        LIMIT 1`,
    )
    .get(folderId, PATROL_LOG_SOURCE);
  return row ?? null;
}

function severityBadge(severity: FindingSeverity): string {
  switch (severity) {
    case 'p1':
      return '`P1`';
    case 'p2':
      return '`P2`';
    case 'warn':
      return '`!`';
    case 'info':
    default:
      return '`i`';
  }
}

const SEVERITY_RANK: Record<FindingSeverity, number> = {
  p1: 0,
  p2: 1,
  warn: 2,
  info: 3,
};

function severityCompare(a: Tier0Finding, b: Tier0Finding): number {
  const sa = SEVERITY_RANK[a.severity] ?? 99;
  const sb = SEVERITY_RANK[b.severity] ?? 99;
  if (sa !== sb) return sa - sb;
  return a.noteId.localeCompare(b.noteId);
}

function formatUtcStamp(ts: number): string {
  const d = new Date(ts);
  const pad = (n: number) => String(n).padStart(2, '0');
  return (
    `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())}` +
    ` ${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())} UTC`
  );
}

function deriveTitle(body: string): string {
  for (const raw of body.split('\n')) {
    const trimmed = raw.trim();
    if (trimmed.length === 0) continue;
    const cleaned = trimmed.replace(/^[#\-*\s>]+/, '').trim();
    if (cleaned.length === 0) continue;
    return cleaned.length > 200 ? cleaned.slice(0, 200) : cleaned;
  }
  return 'Mo Patrol Log';
}
